/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package software.clinica.medica.metropolitana;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author kmonn
 */
public class PantallaMain extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMain
     */
    public PantallaMain() {
        initComponents();
        this.setVisible(true):
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistroPacientes = new javax.swing.JButton();
        btnGestorCitas = new javax.swing.JButton();
        btnRegistrosMedicos = new javax.swing.JButton();
        btnFarmacia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla Gestion");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnRegistroPacientes.setForeground(new java.awt.Color(51, 0, 51));
        btnRegistroPacientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\kmonn\\Downloads\\Logos API CLINICA\\registro.png")); // NOI18N
        btnRegistroPacientes.setText("Registro de Pacientes");
        btnRegistroPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPacientesActionPerformed(evt);
            }
        });

        btnGestorCitas.setForeground(new java.awt.Color(0, 51, 51));
        btnGestorCitas.setIcon(new javax.swing.ImageIcon("C:\\Users\\kmonn\\Downloads\\Logos API CLINICA\\cita-medica.png")); // NOI18N
        btnGestorCitas.setText("Gestion Citas Medicas");
        btnGestorCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestorCitasActionPerformed(evt);
            }
        });

        btnRegistrosMedicos.setForeground(new java.awt.Color(51, 0, 51));
        btnRegistrosMedicos.setIcon(new javax.swing.ImageIcon("C:\\Users\\kmonn\\Downloads\\Logos API CLINICA\\historial-medico.png")); // NOI18N
        btnRegistrosMedicos.setText("Registros Medicos");
        btnRegistrosMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosMedicosActionPerformed(evt);
            }
        });

        btnFarmacia.setForeground(new java.awt.Color(51, 0, 51));
        btnFarmacia.setIcon(new javax.swing.ImageIcon("C:\\Users\\kmonn\\Downloads\\Logos API CLINICA\\farmacia.png")); // NOI18N
        btnFarmacia.setText("Farmacia");
        btnFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmaciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistroPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestorCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroPacientes)
                    .addComponent(btnGestorCitas))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFarmacia)
                    .addComponent(btnRegistrosMedicos))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPacientesActionPerformed
        RegistroPacientes pantalla = new RegistroPacientes(){
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroPacientesActionPerformed

    private void btnGestorCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestorCitasActionPerformed
        GestorCitas pantalla = new GestorCitas();
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestorCitasActionPerformed

    private void btnRegistrosMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosMedicosActionPerformed
        RegistrosMedicos pantalla = new RegistrosMedicos();
        pantalla.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRegistrosMedicosActionPerformed

    private void btnFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmaciaActionPerformed
        Farmacia pantalla = new Farmacia();
        pantalla.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btnFarmaciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new PantallaMain().setVisible(true);
                
            }
            
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFarmacia;
    private javax.swing.JButton btnGestorCitas;
    private javax.swing.JButton btnRegistroPacientes;
    private javax.swing.JButton btnRegistrosMedicos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
